/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_juanmolina_11621058;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hwan
 */
public class main extends javax.swing.JFrame {

    archivo ap = new archivo("./carros.cbm");
    ArrayList<carro> carrosTemp = new ArrayList();
    ArrayList<carro> carrosCarrera = new ArrayList();
    public main() {
        initComponents();
        ap.cargarArchivo();
        carrosTemp = ap.getCarros();
        for (carro temp : carrosTemp) {
            carrosLista.addItem(temp.getNombre());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        pistaLabel = new javax.swing.JLabel();
        largoLabel = new javax.swing.JLabel();
        pistaLabelEdit = new javax.swing.JLabel();
        largoLabelEdit = new javax.swing.JLabel();
        nombrePistaLabel = new javax.swing.JLabel();
        largoPistaLabel = new javax.swing.JLabel();
        nombrePistaField = new javax.swing.JTextField();
        largoPistaField = new javax.swing.JTextField();
        botonPista = new javax.swing.JButton();
        reinicioBoton = new javax.swing.JButton();
        listaTipo = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        carrosLista = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        color = new javax.swing.JToggleButton();
        idField = new javax.swing.JTextField();
        corredorField = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        carreraBarra = new javax.swing.JProgressBar();
        comenzar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCorredores = new javax.swing.JTable();
        estado = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pistaLabel.setText("Pista:");
        getContentPane().add(pistaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 40, -1, -1));

        largoLabel.setText("Largo:");
        getContentPane().add(largoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 40, -1, -1));

        pistaLabelEdit.setText("__________");
        getContentPane().add(pistaLabelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 40, -1, -1));

        largoLabelEdit.setText("__________");
        getContentPane().add(largoLabelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 40, -1, -1));

        nombrePistaLabel.setText("Nombre Pista:");
        getContentPane().add(nombrePistaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 370, -1, -1));

        largoPistaLabel.setText("Largo Pista:");
        getContentPane().add(largoPistaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 412, -1, -1));

        nombrePistaField.setMaximumSize(new java.awt.Dimension(50, 16));
        nombrePistaField.setMinimumSize(new java.awt.Dimension(50, 16));
        nombrePistaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePistaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nombrePistaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 367, 88, -1));

        largoPistaField.setMaximumSize(new java.awt.Dimension(50, 16));
        largoPistaField.setMinimumSize(new java.awt.Dimension(50, 16));
        largoPistaField.setPreferredSize(new java.awt.Dimension(64, 22));
        largoPistaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largoPistaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(largoPistaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 409, 88, -1));

        botonPista.setText("USAR PISTA");
        botonPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPistaActionPerformed(evt);
            }
        });
        getContentPane().add(botonPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 490, 117, -1));

        reinicioBoton.setText("REINICIAR PISTA");
        reinicioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinicioBotonActionPerformed(evt);
            }
        });
        getContentPane().add(reinicioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 538, -1, -1));

        listaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "McQueen", "Convertible", "Nascar"}));
        listaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaTipoActionPerformed(evt);
            }
        });
        getContentPane().add(listaTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 487, 117, -1));

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 367, 104, -1));

        carrosLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        carrosLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrosListaActionPerformed(evt);
            }
        });
        getContentPane().add(carrosLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 367, 117, -1));

        jLabel1.setText("Numero Identificador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 412, -1, -1));

        jLabel2.setText("Nombre Corredor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 443, -1, -1));

        color.setText("COLOR");
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 490, 107, -1));
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 409, 107, -1));
        getContentPane().add(corredorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 440, 107, -1));

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 538, 107, -1));
        getContentPane().add(carreraBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 83, 457, 73));

        comenzar.setText("COMENZAR");
        comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarActionPerformed(evt);
            }
        });
        getContentPane().add(comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 37, -1, -1));

        tablaCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },

            new String [] {
                "Identificador", "Corredor", "Distancia"
            }
        ));
        tablaCorredores.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tablaCorredores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 162, 457, 174));

        estado.setText("PAUSA");
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 37, 94, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPistaActionPerformed
        pistaLabelEdit.setText(nombrePistaField.getText());
        nombrePistaField.setText("");
        largoLabelEdit.setText(largoPistaField.getText());
        largoPistaField.setText("");
        
        
        
    }//GEN-LAST:event_botonPistaActionPerformed

    private void reinicioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinicioBotonActionPerformed
        pistaLabelEdit.setText("");
        nombrePistaField.setText("");
        largoLabelEdit.setText("");
        largoPistaField.setText("");
        
        
    }//GEN-LAST:event_reinicioBotonActionPerformed

    private void listaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTipoActionPerformed
        
    }//GEN-LAST:event_listaTipoActionPerformed

    private void nombrePistaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePistaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePistaFieldActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        Color colores = JColorChooser.showDialog(null,"Seleccione el Color", Color.black);
        color.setBackground(colores);
    }//GEN-LAST:event_colorActionPerformed

    private void largoPistaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largoPistaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largoPistaFieldActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        int tempId = Integer.parseInt(idField.getText());
        
        
        if (carrosTemp.contains(tempId)) {
            JOptionPane.showMessageDialog(this, "Este ID de corredor ya existe!");
            idField.setText("");
        } else {
            idField.setText("");

            String tempCorredor = corredorField.getText();
            corredorField.setText("");

            Color tempColor = color.getBackground();

            String tempTipo = listaTipo.getActionCommand();

            carro temp = new carro(tempId, tempCorredor, tempTipo, tempColor);
            carrosTemp.add(temp);

            ap.cargarArchivo();
            ap.setCarro(temp);
            carrosLista.addItem(tempCorredor);
            ap.escribirArchivo();
            JOptionPane.showMessageDialog(this,
                    "Corredor Guardado Exitosamente");
        }
        
    }//GEN-LAST:event_guardarActionPerformed

    private void carrosListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrosListaActionPerformed
        
    }//GEN-LAST:event_carrosListaActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String nombreTemp = carrosTemp.get(carrosLista.getSelectedIndex()-1).getNombre();
        int idTemp = carrosTemp.get(carrosLista.getSelectedIndex()-1).getId();
        carrosCarrera.add(carrosTemp.get(carrosLista.getSelectedIndex()-1));
        DefaultTableModel model = (DefaultTableModel) tablaCorredores.getModel();
        model.addRow(new Object[]{idTemp, nombreTemp, 0});

    }//GEN-LAST:event_agregarActionPerformed

    private void comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarActionPerformed
        ab.start();
    }//GEN-LAST:event_comenzarActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        AbstractButton abstractButton = (AbstractButton) evt.getSource();
        boolean selected = abstractButton.getModel().isSelected();

        if(selected){
            estado.setText("REANUDAR");
            ab.setAvanzar(false);
        } else {
            estado.setText("PAUSE");
            ab.setAvanzar(true);
        }
    }//GEN-LAST:event_estadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton botonPista;
    private javax.swing.JProgressBar carreraBarra;
    private javax.swing.JComboBox<String> carrosLista;
    private javax.swing.JToggleButton color;
    private javax.swing.JButton comenzar;
    private javax.swing.JTextField corredorField;
    private javax.swing.JToggleButton estado;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField idField;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel largoLabel;
    private javax.swing.JLabel largoLabelEdit;
    private javax.swing.JTextField largoPistaField;
    private javax.swing.JLabel largoPistaLabel;
    private javax.swing.JComboBox<String> listaTipo;
    private javax.swing.JTextField nombrePistaField;
    private javax.swing.JLabel nombrePistaLabel;
    private javax.swing.JLabel pistaLabel;
    private javax.swing.JLabel pistaLabelEdit;
    private javax.swing.JButton reinicioBoton;
    private javax.swing.JTable tablaCorredores;
    // End of variables declaration//GEN-END:variables
barra ab;
    
}
