/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_juanmolina_11621058;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hwan
 */
public class main extends javax.swing.JFrame {

    archivo ap = new archivo("./carros.cbm");
    ArrayList<carro> carrosTemp = new ArrayList();
    
    public main() {
        initComponents();
        ap.cargarArchivo();
        carrosTemp = ap.getCarros();
        
        for (carro temp : carrosTemp) {
            carrosLista.addItem(temp.getNombre());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        pistaLabel = new javax.swing.JLabel();
        largoLabel = new javax.swing.JLabel();
        pistaLabelEdit = new javax.swing.JLabel();
        largoLabelEdit = new javax.swing.JLabel();
        nombrePistaLabel = new javax.swing.JLabel();
        largoPistaLabel = new javax.swing.JLabel();
        nombrePistaField = new javax.swing.JTextField();
        largoPistaField = new javax.swing.JTextField();
        botonPista = new javax.swing.JButton();
        reinicioBoton = new javax.swing.JButton();
        listaTipo = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        carrosLista = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        color = new javax.swing.JToggleButton();
        idField = new javax.swing.JTextField();
        corredorField = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        comenzar = new javax.swing.JButton();
        pausar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCorredores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pistaLabel.setText("Pista:");

        largoLabel.setText("Largo:");

        pistaLabelEdit.setText("__________");

        largoLabelEdit.setText("__________");

        nombrePistaLabel.setText("Nombre Pista:");

        largoPistaLabel.setText("Largo Pista:");

        nombrePistaField.setMaximumSize(new java.awt.Dimension(50, 16));
        nombrePistaField.setMinimumSize(new java.awt.Dimension(50, 16));
        nombrePistaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePistaFieldActionPerformed(evt);
            }
        });

        largoPistaField.setMaximumSize(new java.awt.Dimension(50, 16));
        largoPistaField.setMinimumSize(new java.awt.Dimension(50, 16));
        largoPistaField.setPreferredSize(new java.awt.Dimension(64, 22));
        largoPistaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largoPistaFieldActionPerformed(evt);
            }
        });

        botonPista.setText("USAR PISTA");
        botonPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPistaActionPerformed(evt);
            }
        });

        reinicioBoton.setText("REINICIAR PISTA");
        reinicioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinicioBotonActionPerformed(evt);
            }
        });

        listaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "McQueen", "Convertible", "Nascar"}));
        listaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaTipoActionPerformed(evt);
            }
        });

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        carrosLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        carrosLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrosListaActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero Identificador");

        jLabel2.setText("Nombre Corredor");

        color.setText("COLOR");
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        comenzar.setText("COMENZAR");

        pausar.setText("PAUSAR");
        pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausarActionPerformed(evt);
            }
        });

        tablaCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Corredor", "Distancia"
            }
        ));
        jScrollPane1.setViewportView(tablaCorredores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carrosLista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listaTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idField)
                            .addComponent(corredorField)
                            .addComponent(color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(reinicioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonPista, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombrePistaLabel)
                                    .addComponent(largoPistaLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombrePistaField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(largoPistaField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(comenzar)
                            .addGap(18, 18, 18)
                            .addComponent(pausar)
                            .addGap(30, 30, 30)
                            .addComponent(pistaLabel)
                            .addGap(18, 18, 18)
                            .addComponent(pistaLabelEdit)
                            .addGap(43, 43, 43)
                            .addComponent(largoLabel)
                            .addGap(18, 18, 18)
                            .addComponent(largoLabelEdit))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comenzar)
                    .addComponent(pausar)
                    .addComponent(pistaLabel)
                    .addComponent(largoLabel)
                    .addComponent(pistaLabelEdit)
                    .addComponent(largoLabelEdit))
                .addGap(24, 24, 24)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(carrosLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(corredorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(listaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombrePistaLabel)
                            .addComponent(nombrePistaField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(largoPistaLabel)
                            .addComponent(largoPistaField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonPista)
                            .addComponent(color))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reinicioBoton)
                            .addComponent(guardar))))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPistaActionPerformed
        pistaLabelEdit.setText(nombrePistaField.getText());
        nombrePistaField.setText("");
        largoLabelEdit.setText(largoPistaField.getText());
        largoPistaField.setText("");
    }//GEN-LAST:event_botonPistaActionPerformed

    private void reinicioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinicioBotonActionPerformed
        pistaLabelEdit.setText("");
        nombrePistaField.setText("");
        largoLabelEdit.setText("");
        largoPistaField.setText("");
    }//GEN-LAST:event_reinicioBotonActionPerformed

    private void listaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTipoActionPerformed
        
    }//GEN-LAST:event_listaTipoActionPerformed

    private void nombrePistaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePistaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePistaFieldActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        Color colores = JColorChooser.showDialog(null,"Seleccione el Color", Color.black);
        color.setBackground(colores);
    }//GEN-LAST:event_colorActionPerformed

    private void largoPistaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largoPistaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largoPistaFieldActionPerformed

    private void pausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pausarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        int tempId = Integer.parseInt(idField.getText());
        if(carrosTemp.contains(tempId)){
            JOptionPane.showMessageDialog(this,"Este ID de corredor ya existe!");
            idField.setText("");
        } else {
            idField.setText("");

            String tempCorredor = corredorField.getText();
            corredorField.setText("");

            Color tempColor = color.getBackground();

            String tempTipo = listaTipo.getActionCommand();

            carro temp = new carro(tempId, tempCorredor, tempTipo, tempColor);

            ap.cargarArchivo();
            ap.setCarro(temp);
            ap.escribirArchivo();
            JOptionPane.showMessageDialog(this,
                    "Corredor Guardado Exitosamente");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void carrosListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrosListaActionPerformed
        
    }//GEN-LAST:event_carrosListaActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String nombreTemp = carrosTemp.get(carrosLista.getSelectedIndex()).getNombre();
        int idTemp = carrosTemp.get(carrosLista.getSelectedIndex()).getId();
        
        DefaultTableModel model = (DefaultTableModel) tablaCorredores.getModel();
        model.addRow(new Object[]{idTemp, nombreTemp, ""});
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton botonPista;
    private javax.swing.JComboBox<String> carrosLista;
    private javax.swing.JToggleButton color;
    private javax.swing.JButton comenzar;
    private javax.swing.JTextField corredorField;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField idField;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel largoLabel;
    private javax.swing.JLabel largoLabelEdit;
    private javax.swing.JTextField largoPistaField;
    private javax.swing.JLabel largoPistaLabel;
    private javax.swing.JComboBox<String> listaTipo;
    private javax.swing.JTextField nombrePistaField;
    private javax.swing.JLabel nombrePistaLabel;
    private javax.swing.JButton pausar;
    private javax.swing.JLabel pistaLabel;
    private javax.swing.JLabel pistaLabelEdit;
    private javax.swing.JButton reinicioBoton;
    private javax.swing.JTable tablaCorredores;
    // End of variables declaration//GEN-END:variables
}
